name: camo
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - accelerate=1.7.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - albucore=0.0.24
  - albumentations=2.0.8
  - annotated-types=0.6.0
  - aom=3.6.0
  - arrow-cpp=19.0.0
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - click=8.1.8
  - coloredlogs=15.0.1
  - cuda-cccl_linux-64=12.4.127
  - cuda-crt-dev_linux-64=12.4.131
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-dev_linux-64=12.4.127
  - cuda-cudart-static=12.4.127
  - cuda-cudart-static_linux-64=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.4.127
  - cuda-driver-dev_linux-64=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvcc=12.4.131
  - cuda-nvcc-dev_linux-64=12.4.131
  - cuda-nvcc-impl=12.4.131
  - cuda-nvcc-tools=12.4.131
  - cuda-nvcc_linux-64=12.4.131
  - cuda-nvdisasm=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-dev_linux-64=12.4.131
  - cuda-nvvm-impl=12.4.131
  - cuda-nvvm-tools=12.4.131
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - cyrus-sasl=2.1.28
  - cython=3.0.11
  - datasets=2.14.4
  - dav1d=1.2.1
  - deprecated=1.2.13
  - diffusers=0.33.1
  - dill=0.3.7
  - easydict=1.13
  - eigen=3.4.0
  - eval-type-backport=0.2.2
  - expat=2.6.4
  - ffmpeg=6.1.1
  - filelock=3.17.0
  - flatdict=4.0.1
  - fontconfig=2.14.2
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - huggingface_hub=0.31.2
  - humanfriendly=10.0
  - icu=73.1
  - idna=3.7
  - imageio=2.37.0
  - importlib-metadata=8.5.0
  - insightface=0.7.3
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libllvm19=19.1.7
  - libmlir19=19.1.7
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=2.38.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lit=19.1.7
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - magma=2.7.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - mysql=8.4.0
  - nccl=2.21.5.1
  - ncurses=6.4
  - networkx=3.4.2
  - numexpr=2.10.1
  - ocl-icd=2.3.2
  - onnx=1.17.0
  - onnxruntime=1.20.1
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.0
  - opentelemetry-api=1.30.0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pip=25.1
  - pixman=0.40.0
  - prettytable=3.5.0
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pyarrow=19.0.0
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - s2n=1.3.27
  - safetensors=0.5.3
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=72.1.0
  - simsimd=6.4.9
  - six=1.17.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sqlite=3.45.3
  - stringzilla=3.12.5
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tifffile=2025.2.18
  - tk=8.6.14
  - tokenizers=0.21.0
  - torchtriton=3.1.0
  - tqdm=4.67.1
  - transformers=4.49.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - wrapt=1.17.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annoy==1.17.3
      - asttokens==3.0.0
      - comm==0.2.2
      - contourpy==1.3.2
      - controlnet-aux==0.0.1
      - cycler==0.12.1
      - decorator==5.2.1
      - deepspeed==0.17.1
      - einops==0.8.1
      - executing==2.2.0
      - facenet-pytorch==2.6.0
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hjson==3.1.0
      - ipython==9.3.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jeepney==0.9.0
      - jupyterlab-widgets==3.0.15
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - msgpack==1.1.1
      - ninja==1.11.1.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyfacer==0.0.5
      - pygments==2.19.1
      - pyparsing==3.2.3
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - timm==1.0.15
      - torch==2.2.2
      - torchaudio==2.6.0+cu124
      - torchvision==0.17.2
      - traitlets==5.14.3
      - triton==3.2.0
      - validators==0.35.0
      - wakepy==0.10.2.post1
      - wandb==0.20.1
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14