name: camo
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - conda-forge::flatdict
  - python==3.12.2
  - numpy
  - pydantic
  - pillow
  - tqdm
  - accelerate
  - transformers
  - opencv
  - diffusers
  - click
  - scikit-image
  - insightface